<?php

/**
 * @file
 *   panparks_donate.module
 * Project:panparks.org
 *    Photo donate forms for panparks.org
 *
 * @developers:
 *    Gabor Szanto <hello@szantogabor.com>
 *    http://szantogabor.com
 *
 */

function panparks_donate_form_wilderness_supporter($form, $form_state, $suffix = FALSE) {
  drupal_add_js(drupal_get_path('module', 'panparks_donate') . '/panparks_donate.js');
  $form = array(
    'amountSelector' => array(
      '#title' => t('I want to give:'),
      '#type' => 'radios',
      '#default_value' => 10,
      '#options' => array(
        '10' => $suffix ? '<span class="value">€10</span><span class="suffix">' . t('will buy you guaranteed protection of 10 hectares in Europe for a year') .'</span>' : '€10',
        '25' =>$suffix ? '<span class="value">€25</span><span class="suffix">' . t('will enable us to mark the most valuable wilderness areas with signs') .'</span>' : '€25',
        '100' => $suffix ? '<span class="value">€100</span><span class="suffix">' . t('will ensure monitoring of animals for 2 months') .'</span>' : '€100',
      ),
    ),
    'uniqueAmount' => array(
      '#type' => 'textfield',
      '#title' => t('Or choose your amount €'),
      '#size'=> 15,
      //'#field_prefix' => '€',
    ),
    'submit' => array(
      '#type' => 'submit',
      '#value' => t('Donate'),
      '#attributes' => array(
        'id' => 'ws_submit'
      )
    ),
    'amount' => array(
      '#type' => 'hidden',
      '#value' => 10,
    ),
    '#submit' => array('panparks_donate_form_submit'),
  );
  return $form;
}

function panparks_donate_form_support_documentary($form, $form_state, $suffix = FALSE) {
  drupal_add_js(drupal_get_path('module', 'panparks_donate') . '/panparks_donate.js');
  $form = array(
    'amountSelector' => array(
      '#title' => t('I want to give:'),
      '#type' => 'radios',
      '#default_value' => 10,
      '#options' => array(
        '10' => $suffix ? '<span class="value">€10</span><span class="suffix">' . t('contribution to equipment') .'</span>' : '€10',
        '15' => $suffix ? '<span class="value">€15</span><span class="suffix">' . t('one day food supply') .'</span>' : '€15',
        '20' => $suffix ? '<span class="value">€20</span><span class="suffix">' . t('education about wilderness for youth') .'</span>' : '€20',
      ),
    ),
    'submit' => array(
      '#type' => 'submit',
      '#value' => t('Donate'),
      '#attributes' => array(
        'id' => 'sd_submit'
      )
    ),
    'amount' => array(
      '#type' => 'hidden',
      '#value' => 10,
    ),
    '#submit' => array('panparks_donate_form_submit'),
  );
  return $form;
}

function panparks_donate_form_submit($form, &$form_state) {
  $url = url('node/3440', array('absolute' => TRUE, 'query' => array('default_amount' => $form_state['input']['amount'])));
  $form_state['redirect'] = $url;
}
/*
 * Implements hook_block_MODULE_BLOCK_ID_alter
 * Insert form after content block Became a wilderness supporter
 */
function panparks_donate_block_view_bean_11_alter(&$data, $block) {
  $data['content']['bean'][11]['form'] = array(
    'form' => drupal_get_form('panparks_donate_form_wilderness_supporter', TRUE),
    '#weight' => 100,
  );
  $data['content']['bean'][11]['field_image']['#weight'] = 99;
}

/*
 * Implements hook_block_MODULE_BLOCK_ID_alter
 * Insert form after content after Support the unique documentary of wilderness block
 */
function panparks_donate_block_view_bean_12_alter(&$data, $block) {
  $data['content']['bean'][12]['form'] = array(
    'form' => drupal_get_form('panparks_donate_form_support_documentary', TRUE),
    '#weight' => 100,
  );
  //Increase weight to render after body
  $data['content']['bean'][12]['field_body']['#weight'] = 2;
}

/*
 * Implements hook_block_MODULE_BLOCK_ID_alter
 * Insert form after front page donate block content
 */
function panparks_donate_block_view_bean_3_alter(&$data, $block) {
  $data['content']['bean'][3]['form'] = array(
    'form' => drupal_get_form('panparks_donate_form_wilderness_supporter'),
    '#weight' => 100,
  );
}

/*
 * Implements hook_block_MODULE_BLOCK_ID_alter
 * Insert form after front page donate block content
 */
function panparks_donate_block_view_bean_8_alter(&$data, $block) {
  $data['content']['bean'][3]['form'] = array(
    'form' => drupal_get_form('panparks_donate_form_wilderness_supporter'),
    '#weight' => 100,
  );
}
